### ISSUE TITLE
I can't execute an example

### ISSUE THREAD

**Issue by RochaLAJ** [elenasa/ULAM#106]
Hello!
I was trying to make my first run in Ulam when i had the following error as return: 
`Compile UlamCustomElements.cpp ERROR: Close failed: 512`

Then in the end of the verbose, i have:
```
make: *** [config/Makeulamfile.mk:63: /home/lajnote/experiment/.gen/build/UlamCustomElements.o] Error 1
Error: 1g++ build problem(s) detected
```

I already have build-essential, g++...installed, i am trying to run in a notebook with Zorin OS based on Ubuntu 20.04 LTS. I've installed the ulam .deb from launchpad. 
Example: https://github.com/elenasa/ULAM/wiki/Ulam-Programming-Language
Thank you for your time!

**Comment by DaveAckley** [comment]
Hi, sorry for the trouble!   Unfortunately the tutorial stuff hasn't been updated for a while -- note it's asking for Ubuntu 16.04 latest!  The g++ compiler's changed over the years and it's totally easy to believe the old packages would have troubles.

Most likely you'll need to build from the github repos.  http://robust.cs.unm.edu/doku.php?id=dev:clone_from_github
