### ISSUE TITLE
R button on GUI   Right click mouse adds but can't remove

### ISSUE THREAD

**Issue by wrapperband** [elenasa/ULAM#81]
mfzrun SiteWriter.mfz

I can't find how to remove the "resources" display, once activated with the mouse right click

**Comment by DaveAckley** [comment]
An 'AtomView' panel is currently dismissed by hitting Escape while the mouse is inside the panel.

**Comment by DaveAckley** [comment]
As of MFM commit d792e2a, the 'X to close' icon is finally back in the AtomViewPanel.
